# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test
spec:
  selector:
    matchLabels:
      app: django-test
  replicas: 2
  template:
    metadata:
      labels:
        app: django-test
    spec:
      containers:
      - name: django-test
        image: registry.cn-shenzhen.aliyuncs.com/0671/django-test:latest
        ports:
        - containerPort: 8000
