# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: django-test-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 32199
  selector:
    app: django-test
